## Q1. Create two numpy arrays. The first array, called arr1 should be of one dimension and consist of six elements of float type. The second array, called arr2 should be of two dimensions and each sub-array should consist of 5 elements of string type. Display these two numpy arrays.

In [12]:
import numpy as np
arr1 = np.array([1.2, 2.4, 3.5, 4.1, 5.9, 6.8])

arr2 = np.array([['Apple', 'Mango', 'Grapes', 'Banana', 'kiwi'],['Strawberry', 'Lichi', 'Orange', 'Pappaya', 'Berries']])

print('arr1 : ',arr1)

print(' '*50)

print('arr2 : ',arr2)

arr1 :  [1.2 2.4 3.5 4.1 5.9 6.8]
                                                  
arr2 :  [['Apple' 'Mango' 'Grapes' 'Banana' 'kiwi']
 ['Strawberry' 'Lichi' 'Orange' 'Pappaya' 'Berries']]


## Q2. For the arrays arr1 and arr2 created in Q.No.1, display the following properties: data type and dimensions. Reshape arr1 into a two dimensional array of 2 rows and three columns, and display the reshaped array. Similarly, reshape arr2 into a single dimensional array and display the reshaped array.

In [2]:
print('Type is : ', type(arr1))
print('Datatype arr1 : ', arr1.dtype)

print('*'*50)

print('Datatype arr2 : ', arr2.dtype)
print('Type is : ', type(arr2))

print(' '*50)

arr1 = arr1.reshape(2,3)
print('arr1 : ', arr1)

print(' '*50)

arr2 = arr2.flatten()
print('arr2 : ', arr2)

Type is :  <class 'numpy.ndarray'>
Datatype arr1 :  float64
**************************************************
Datatype arr2 :  <U10
Type is :  <class 'numpy.ndarray'>
                                                  
arr1 :  [[1.2 2.4 3.5]
 [4.1 5.9 6.8]]
                                                  
arr2 :  ['Apple' 'Mango' 'Grapes' 'Banana' 'kiwi' 'Strawberry' 'Lichi' 'Orange'
 'Pappaya' 'Berries']


## Q3. Create a two dimensional array called arr3, of 3 rows and 4 columns which is initialized to zeroes. Create another single dimensional array called arr4, with 6 elements and which is initialized to ones. The type of arr4 is int.

In [3]:
arr3 = np.zeros([3,4], dtype=float)

arr4 = np.ones(6,dtype=int)

print('arr3 : ', arr3)

print(' '*50)

print('arr4 : ', arr4)

arr3 :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
                                                  
arr4 :  [1 1 1 1 1 1]


## Q4.Create a list called list1 with the elements 10,20,30,40,50. Now, create a numpy array called arr5 from list1, using the method asarray. The data type of arr5 is float. Similarly, create another array called arr6, from list1, using the method fromiter, whose data type is int. Display arr5 and arr6.

In [4]:
list1 = [10,20,30,40,50]
print(list1)
print(type(list1))

[10, 20, 30, 40, 50]
<class 'list'>


In [5]:
arr5 = np.asarray(list1,dtype=float)

print('arr5 : ', arr5)
print(arr5.dtype)

arr5 :  [10. 20. 30. 40. 50.]
float64


In [6]:
arr6 = np.fromiter(list1,dtype = int)
print('arr6 : ', arr6)
print(arr6.dtype)

arr6 :  [10 20 30 40 50]
int32


## Q5. Create a numpy array called arr7 using the method arange. The starting value of this array is 12 and ending value is 99, with a step size of 3. Use the linspace method to create another array called arr8, where the starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements.

In [7]:
import numpy as np
arr7 = np.arange(12,99,3)
print(arr7)

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96]


In [8]:
arr8 = np.linspace(12,99,50)
print(arr8)

[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


## Q6. In the array arr2 defined in Q.No. 1, what is the output of the following statements: print(arr2), print(arr2[0:1]), print(arr2[1][3]), print (arr2[1])

In [13]:
print(arr2)

[['Apple' 'Mango' 'Grapes' 'Banana' 'kiwi']
 ['Strawberry' 'Lichi' 'Orange' 'Pappaya' 'Berries']]


In [14]:
print(arr2[0:1])

[['Apple' 'Mango' 'Grapes' 'Banana' 'kiwi']]


In [15]:
print(arr2[1][3])

Pappaya


In [16]:
print(arr2[1])

['Strawberry' 'Lichi' 'Orange' 'Pappaya' 'Berries']


## Q7. Create a two dimensional array called arr9 with the following elements: [101, 322, 768], [233, 124, 390], [534, 122, 216]. From arr9, create an array called arr10 which contains the elements 101, 322, 390, 122 using advanced integer indexing. Create another array called arr11 which contains elements of first and second rows, and second and third columns using slicing operations.

In [17]:
import numpy as np
arr9 = np.array([[101,322,768],[233,124,390],[534,122,216]])

print(arr9)

[[101 322 768]
 [233 124 390]
 [534 122 216]]


In [18]:
arr10 = arr9[0][0],arr9[0][1],arr9[1][2],arr9[2][1]

print(arr10)

(101, 322, 390, 122)


In [19]:
arr11 =  arr9[0:2][1:3]

print(arr11)

[[233 124 390]]


## Q8. From array arr9 created in Q.No. 7, find all elements greater than 200 using boolean indexing, find all non-NaN elements, and find all non-float elements. Find the result of adding arrays arr9 and another array of 3 elements, using the concept of broadcasting.

In [20]:
arr9

array([[101, 322, 768],
       [233, 124, 390],
       [534, 122, 216]])

In [21]:
print("Elements are greater than 200 : ")

arr12 = (arr9[arr9>200])
print(arr12)

Elements are greater than 200 : 
[322 768 233 390 534 216]


In [22]:
arr13 = (arr9[~np.isnan(arr9)])
print(arr13)

[101 322 768 233 124 390 534 122 216]


In [23]:
arr14 = (arr9[arr9.dtype!='float'])

print(arr14)

[[[101 322 768]
  [233 124 390]
  [534 122 216]]]


In [24]:
arr15 = np.array([100,101,102])

arr16 = arr9 + arr15

print(arr16)

[[201 423 870]
 [333 225 492]
 [634 223 318]]


## Q9. For the array arr9, find its transpose. Find the result of joining the arrays arr1 and arr4 along axis 0.

In [25]:
print('Transpose of arr9 :')
print(arr9.T)
print('*'*50)

arr1 = np.array([1,2,3,4,5,6])
arr4 = np.array([1,1,1,1,1,1])
print('Joining the two arrays arr1 and arr4 along axis 0 : ')
print(np.concatenate((arr1,arr4), axis=0))

Transpose of arr9 :
[[101 233 534]
 [322 124 122]
 [768 390 216]]
**************************************************
Joining the two arrays arr1 and arr4 along axis 0 : 
[1 2 3 4 5 6 1 1 1 1 1 1]


## Q10. Using any two 2-dimensional arrays, demonstrate the working of the methods, hstack, vstack, hsplit and vsplit

In [27]:
arr17 = np.array([[1,2],[3,4]])

print(arr17)

[[1 2]
 [3 4]]


In [28]:
print (np.hstack(arr17))

[1 2 3 4]


In [29]:
print(np.vstack(arr17))

[[1 2]
 [3 4]]


In [30]:
print(np.hsplit(arr17,2))

[array([[1],
       [3]]), array([[2],
       [4]])]


In [31]:
print(np.vsplit(arr17,2))

[array([[1, 2]]), array([[3, 4]])]
